spring:
  config:
    import:
      - optional:shared/application-database.yml
      - optional:shared/application-kafka.yml
      - optional:shared/application-schema.yml
      - optional:shared/application-logging.yml
      - optional:shared/application-jwt.yml

server:
  port: 9001