spring:
  application:
    name: authentication-service

  profiles:
    include:
      - application-database
      - application-kafka
      - application-schema
      - application-logging
      - application-jwt

server:
  port: 9001