spring:
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="LWWZRCCP3MZTXCO2"
        password="cfltuK9RJEAI10Rty5MI2/VyHZIM/kOK5WQuQgdNxUr79S5u3cE+RXxwLBHsXRMA";
      schema.registry.url: "https://psrc-l622j.us-east-2.aws.confluent.cloud"
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: "2YUXK4OUNGP6IDKJ:cfltrUc8ibGI1231r2fRWoZPu4JE4qB+SJME0C3pYIo4a96ha7Nqfu35dRWN1SoQ"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific.avro.reader: true

kafka:
  topics:
    userVerification: user_verification_events
    userCreated: user_created_events